# Purpose of this playbook is only local render preview and build validation as a part of PR verifier.
# Docs are rendered and published in separate repository for all DBOS projects.

site:
  url: http://localhost/
# The following property is not needed as long as we start in ROOT
# start_page: wiki::ROOT.adoc

content:
  sources:
    - url: .
      start_path: content
      branches: HEAD

antora:
  extensions:
    # lunr-extension for search
    - require: '@antora/lunr-extension'

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    #url: https://github.com/camptocamp/devops-stack-antora-ui/releases/download/main-latest/ui-bundle.zip
    #url: https://github.com/bonitasoft/bonita-documentation-theme/releases/download/v1.15.0/bonita-documentation-theme-v1.15.0.zip

asciidoc:
  attributes:
    source-highlighter: 'coderay'
