= Packaging and Distributing Applications for Kubernetes

:link: https://springone.io/2021/sessions/packaging-and-distributing-applications-for-kubernetes
:author: Ian Zink as Staff Software Engineer, VMware
:author2: Nitasha Verma as Solutions Engineer, VMware
:length: 24:55
:date: 08-09-2021
:language: English 🇺🇸
:quote: Carvel is a composable Kubernetes tool suite.
:track: Architecture

:rating: 3
:pros: Well-structured presentation with a demo, they were able to find a workaround for an unexpected error they faced during the demo
:cons: Overly abstract terms (configuration, bundle, registers...) and commands in the demo were insufficiently described

include::partial$session.adoc[]

Relocating K8S configurations and containers into the hands of their customers as a secure, consistent, and unified distribution within the framework of their existing ecosystem is clumsy.

Application lifecycle (packaging and deployment on K8S): Author Configuration -> Package and Distribution -> Customizing Configuration -> Deploy to Cluster.

Carvel is a composable Kubernetes tool suite, which provides a set of reliable, single-purpose, composable tools that aid in your application building, configuration, and deployment to Kubernetes.

Basic tools:

* `ytt`: Template and overlay K8S via YAML structures.
* `kbld`: Build or reference container images in K8S configuration in an immutable way.
* `kapp`: Install, upgrade, and delete multiple K8S resources as one application.
* `imgpkg`: Bundle and relocate application configuration (with images) via Docker registers.
